// Code generated by go-swagger; DO NOT EDIT.

// Package restapi greeter
//
//	Minimal API used to demonstrate how to plug custom net/http middleware
//	into a server generated by go-swagger.
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
