// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Minimal API used to demonstrate how to plug custom net/http middleware\ninto a server generated by go-swagger.\n",
    "title": "greeter",
    "version": "0.1.0"
  },
  "basePath": "/api",
  "paths": {
    "/greet": {
      "get": {
        "tags": [
          "greeter"
        ],
        "summary": "Return a default greeting.",
        "operationId": "greet",
        "responses": {
          "200": {
            "description": "greeting",
            "schema": {
              "$ref": "#/definitions/greeting"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/greet/{name}": {
      "get": {
        "tags": [
          "greeter"
        ],
        "summary": "Return a greeting addressed to the caller.",
        "operationId": "greetName",
        "parameters": [
          {
            "type": "string",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "greeting",
            "schema": {
              "$ref": "#/definitions/greeting"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "greeting": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Minimal API used to demonstrate how to plug custom net/http middleware\ninto a server generated by go-swagger.\n",
    "title": "greeter",
    "version": "0.1.0"
  },
  "basePath": "/api",
  "paths": {
    "/greet": {
      "get": {
        "tags": [
          "greeter"
        ],
        "summary": "Return a default greeting.",
        "operationId": "greet",
        "responses": {
          "200": {
            "description": "greeting",
            "schema": {
              "$ref": "#/definitions/greeting"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/greet/{name}": {
      "get": {
        "tags": [
          "greeter"
        ],
        "summary": "Return a greeting addressed to the caller.",
        "operationId": "greetName",
        "parameters": [
          {
            "type": "string",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "greeting",
            "schema": {
              "$ref": "#/definitions/greeting"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "greeting": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
