// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Principal principal
//
// swagger:model principal
type Principal string

// Validate validates this principal
func (m Principal) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this principal based on context it is used
func (m Principal) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}
