// Code generated by go-swagger; DO NOT EDIT.

package store

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInventoryGetParams creates a new InventoryGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInventoryGetParams() *InventoryGetParams {
	return NewInventoryGetParamsWithTimeout(cr.DefaultTimeout)
}

// NewInventoryGetParamsWithTimeout creates a new InventoryGetParams object
// with the ability to set a timeout on a request.
func NewInventoryGetParamsWithTimeout(timeout time.Duration) *InventoryGetParams {
	return &InventoryGetParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewInventoryGetParamsWithContext creates a new InventoryGetParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [InventoryGetParams].
func NewInventoryGetParamsWithContext(ctx context.Context) *InventoryGetParams {
	return &InventoryGetParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewInventoryGetParamsWithHTTPClient creates a new InventoryGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewInventoryGetParamsWithHTTPClient(client *http.Client) *InventoryGetParams {
	return &InventoryGetParams{
		HTTPClient: client,
	}
}

/*
InventoryGetParams contains all the parameters to send to the API endpoint

	for the inventory get operation.

	Typically these are written to a http.Request.
*/
type InventoryGetParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the inventory get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InventoryGetParams) WithDefaults() *InventoryGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the inventory get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InventoryGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the inventory get params.
func (o *InventoryGetParams) WithTimeout(timeout time.Duration) *InventoryGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the inventory get params.
func (o *InventoryGetParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the inventory get params.
//
// Deprecated: use the operation call with context to pass the context instead of [InventoryGetParams].
func (o *InventoryGetParams) WithContext(ctx context.Context) *InventoryGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the inventory get params.
//
// Deprecated: use the operation call with context to pass the context instead of [InventoryGetParams].
func (o *InventoryGetParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the inventory get params.
func (o *InventoryGetParams) WithHTTPClient(client *http.Client) *InventoryGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the inventory get params.
func (o *InventoryGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *InventoryGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
