// Code generated by go-swagger; DO NOT EDIT.

package tasks

import (
	"context"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new tasks API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new tasks API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new tasks API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for tasks API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithContentType allows the client to force the Content-Type header
// to negotiate a specific Consumer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithContentType(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ConsumesMediaTypes = []string{mime}
	}
}

// WithContentTypeApplicationJSON sets the Content-Type header to "application/json".
func WithContentTypeApplicationJSON(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/json"}
}

// WithContentTypeApplicationVndGoswaggerExamplesTaskTrackerV1JSON sets the Content-Type header to "application/vnd.goswagger.examples.task-tracker.v1+json".
func WithContentTypeApplicationVndGoswaggerExamplesTaskTrackerV1JSON(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/vnd.goswagger.examples.task-tracker.v1+json"}
}

// WithContentTypeMultipartFormData sets the Content-Type header to "multipart/form-data".
func WithContentTypeMultipartFormData(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"multipart/form-data"}
}

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptApplicationVndGoswaggerExamplesTaskTrackerV1JSON sets the Accept header to "application/vnd.goswagger.examples.task-tracker.v1+json".
func WithAcceptApplicationVndGoswaggerExamplesTaskTrackerV1JSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/vnd.goswagger.examples.task-tracker.v1+json"}
}

// ClientService is the interface for Client methods.
type ClientService interface {
	AddCommentToTask(params *AddCommentToTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddCommentToTaskCreated, error)

	CreateTask(params *CreateTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateTaskCreated, error)

	DeleteTask(params *DeleteTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTaskNoContent, error)

	GetTaskComments(params *GetTaskCommentsParams, opts ...ClientOption) (*GetTaskCommentsOK, error)

	GetTaskDetails(params *GetTaskDetailsParams, opts ...ClientOption) (*GetTaskDetailsOK, error)

	ListTasks(params *ListTasksParams, opts ...ClientOption) (*ListTasksOK, error)

	UpdateTask(params *UpdateTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateTaskOK, error)

	UploadTaskFile(params *UploadTaskFileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UploadTaskFileCreated, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
	AddCommentToTaskadds a comment to a task.

	The comment can contain ___github markdown___ syntax.

Fenced codeblocks etc are supported through pygments.
.

	This method does not support injected context.
	However, timeout and opentracing contexts are honored whenever enabled.

	If you need to pass a specific context, use [Client.AddCommentToTaskContext] instead.
*/
func (a *Client) AddCommentToTask(params *AddCommentToTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddCommentToTaskCreated, error) {
	var ctx context.Context
	if params.Context != nil {
		ctx = params.Context
	} else {
		ctx = context.Background()
	}

	return a.AddCommentToTaskContext(ctx, params, authInfo, opts...)
}

/*
	AddCommentToTaskContextadds a comment to a task.

	The comment can contain ___github markdown___ syntax.

Fenced codeblocks etc are supported through pygments.
.

	Do not use the deprecated [AddCommentToTaskParams.Context] with this method: it would be ignored.
*/
func (a *Client) AddCommentToTaskContext(ctx context.Context, params *AddCommentToTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddCommentToTaskCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewAddCommentToTaskParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "addCommentToTask",
		Method:             "POST",
		PathPattern:        "/tasks/{id}/comments",
		ProducesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AddCommentToTaskReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*AddCommentToTaskCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*AddCommentToTaskDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
	CreateTaskcreates a task object.

	Allows for creating a task.

This operation requires authentication so that we know which user
created the task.
.

	This method does not support injected context.
	However, timeout and opentracing contexts are honored whenever enabled.

	If you need to pass a specific context, use [Client.CreateTaskContext] instead.
*/
func (a *Client) CreateTask(params *CreateTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateTaskCreated, error) {
	var ctx context.Context
	if params.Context != nil {
		ctx = params.Context
	} else {
		ctx = context.Background()
	}

	return a.CreateTaskContext(ctx, params, authInfo, opts...)
}

/*
	CreateTaskContextcreates a task object.

	Allows for creating a task.

This operation requires authentication so that we know which user
created the task.
.

	Do not use the deprecated [CreateTaskParams.Context] with this method: it would be ignored.
*/
func (a *Client) CreateTaskContext(ctx context.Context, params *CreateTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateTaskCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewCreateTaskParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "createTask",
		Method:             "POST",
		PathPattern:        "/tasks",
		ProducesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateTaskReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*CreateTaskCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*CreateTaskDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
	DeleteTaskdeletes a task.

	This is a soft delete and changes the task status to ignored.

.

	This method does not support injected context.
	However, timeout and opentracing contexts are honored whenever enabled.

	If you need to pass a specific context, use [Client.DeleteTaskContext] instead.
*/
func (a *Client) DeleteTask(params *DeleteTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTaskNoContent, error) {
	var ctx context.Context
	if params.Context != nil {
		ctx = params.Context
	} else {
		ctx = context.Background()
	}

	return a.DeleteTaskContext(ctx, params, authInfo, opts...)
}

/*
	DeleteTaskContextdeletes a task.

	This is a soft delete and changes the task status to ignored.

.

	Do not use the deprecated [DeleteTaskParams.Context] with this method: it would be ignored.
*/
func (a *Client) DeleteTaskContext(ctx context.Context, params *DeleteTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTaskNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteTaskParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "deleteTask",
		Method:             "DELETE",
		PathPattern:        "/tasks/{id}",
		ProducesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteTaskReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteTaskNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*DeleteTaskDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
	GetTaskCommentsgets the comments for a task.

	The comments require a size parameter.

.

	This method does not support injected context.
	However, timeout and opentracing contexts are honored whenever enabled.

	If you need to pass a specific context, use [Client.GetTaskCommentsContext] instead.
*/
func (a *Client) GetTaskComments(params *GetTaskCommentsParams, opts ...ClientOption) (*GetTaskCommentsOK, error) {
	var ctx context.Context
	if params.Context != nil {
		ctx = params.Context
	} else {
		ctx = context.Background()
	}

	return a.GetTaskCommentsContext(ctx, params, opts...)
}

/*
	GetTaskCommentsContextgets the comments for a task.

	The comments require a size parameter.

.

	Do not use the deprecated [GetTaskCommentsParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetTaskCommentsContext(ctx context.Context, params *GetTaskCommentsParams, opts ...ClientOption) (*GetTaskCommentsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetTaskCommentsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getTaskComments",
		Method:             "GET",
		PathPattern:        "/tasks/{id}/comments",
		ProducesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetTaskCommentsReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetTaskCommentsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetTaskCommentsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
	GetTaskDetailsgets the details for a task.

	The details view has more information than the card view.

You can see who reported the issue and who last updated it when.

There are also comments for each issue.
.

	This method does not support injected context.
	However, timeout and opentracing contexts are honored whenever enabled.

	If you need to pass a specific context, use [Client.GetTaskDetailsContext] instead.
*/
func (a *Client) GetTaskDetails(params *GetTaskDetailsParams, opts ...ClientOption) (*GetTaskDetailsOK, error) {
	var ctx context.Context
	if params.Context != nil {
		ctx = params.Context
	} else {
		ctx = context.Background()
	}

	return a.GetTaskDetailsContext(ctx, params, opts...)
}

/*
	GetTaskDetailsContextgets the details for a task.

	The details view has more information than the card view.

You can see who reported the issue and who last updated it when.

There are also comments for each issue.
.

	Do not use the deprecated [GetTaskDetailsParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetTaskDetailsContext(ctx context.Context, params *GetTaskDetailsParams, opts ...ClientOption) (*GetTaskDetailsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetTaskDetailsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getTaskDetails",
		Method:             "GET",
		PathPattern:        "/tasks/{id}",
		ProducesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetTaskDetailsReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetTaskDetailsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*GetTaskDetailsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
	ListTaskslists the tasks.

	Allows for specifying a number of filter parameters to

narrow down the results.
Also allows for specifying a **sinceId** and **pageSize** parameter
to page through large result sets.
.

	This method does not support injected context.
	However, timeout and opentracing contexts are honored whenever enabled.

	If you need to pass a specific context, use [Client.ListTasksContext] instead.
*/
func (a *Client) ListTasks(params *ListTasksParams, opts ...ClientOption) (*ListTasksOK, error) {
	var ctx context.Context
	if params.Context != nil {
		ctx = params.Context
	} else {
		ctx = context.Background()
	}

	return a.ListTasksContext(ctx, params, opts...)
}

/*
	ListTasksContextlists the tasks.

	Allows for specifying a number of filter parameters to

narrow down the results.
Also allows for specifying a **sinceId** and **pageSize** parameter
to page through large result sets.
.

	Do not use the deprecated [ListTasksParams.Context] with this method: it would be ignored.
*/
func (a *Client) ListTasksContext(ctx context.Context, params *ListTasksParams, opts ...ClientOption) (*ListTasksOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewListTasksParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "listTasks",
		Method:             "GET",
		PathPattern:        "/tasks",
		ProducesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListTasksReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ListTasksOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*ListTasksDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
	UpdateTaskupdates the details for a task.

	Allows for updating a task.

This operation requires authentication so that we know which user
last updated the task.
.

	This method does not support injected context.
	However, timeout and opentracing contexts are honored whenever enabled.

	If you need to pass a specific context, use [Client.UpdateTaskContext] instead.
*/
func (a *Client) UpdateTask(params *UpdateTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateTaskOK, error) {
	var ctx context.Context
	if params.Context != nil {
		ctx = params.Context
	} else {
		ctx = context.Background()
	}

	return a.UpdateTaskContext(ctx, params, authInfo, opts...)
}

/*
	UpdateTaskContextupdates the details for a task.

	Allows for updating a task.

This operation requires authentication so that we know which user
last updated the task.
.

	Do not use the deprecated [UpdateTaskParams.Context] with this method: it would be ignored.
*/
func (a *Client) UpdateTaskContext(ctx context.Context, params *UpdateTaskParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateTaskOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewUpdateTaskParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "updateTask",
		Method:             "PUT",
		PathPattern:        "/tasks/{id}",
		ProducesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdateTaskReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*UpdateTaskOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*UpdateTaskDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UploadTaskFileadds a file to a task.

The file can't be larger than **5MB**.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.UploadTaskFileContext] instead.
*/
func (a *Client) UploadTaskFile(params *UploadTaskFileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UploadTaskFileCreated, error) {
	var ctx context.Context
	if params.Context != nil {
		ctx = params.Context
	} else {
		ctx = context.Background()
	}

	return a.UploadTaskFileContext(ctx, params, authInfo, opts...)
}

/*
UploadTaskFileContextadds a file to a task.

The file can't be larger than **5MB**.

Do not use the deprecated [UploadTaskFileParams.Context] with this method: it would be ignored.
*/
func (a *Client) UploadTaskFileContext(ctx context.Context, params *UploadTaskFileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UploadTaskFileCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewUploadTaskFileParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "uploadTaskFile",
		Method:             "POST",
		PathPattern:        "/tasks/{id}/files",
		ProducesMediaTypes: []string{"application/vnd.goswagger.examples.task-tracker.v1+json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UploadTaskFileReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*UploadTaskFileCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*UploadTaskFileDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}
