// Code generated by go-swagger; DO NOT EDIT.

package todos

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
	"github.com/go-openapi/swag/stringutils"
)

// NewFindParams creates a new FindParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindParams() *FindParams {
	return NewFindParamsWithTimeout(cr.DefaultTimeout)
}

// NewFindParamsWithTimeout creates a new FindParams object
// with the ability to set a timeout on a request.
func NewFindParamsWithTimeout(timeout time.Duration) *FindParams {
	return &FindParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewFindParamsWithContext creates a new FindParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [FindParams].
func NewFindParamsWithContext(ctx context.Context) *FindParams {
	return &FindParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewFindParamsWithHTTPClient creates a new FindParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindParamsWithHTTPClient(client *http.Client) *FindParams {
	return &FindParams{
		HTTPClient: client,
	}
}

/*
FindParams contains all the parameters to send to the API endpoint

	for the find operation.

	Typically these are written to a http.Request.
*/
type FindParams struct {

	// XRateLimit.
	//
	// Format: int32
	XRateLimit int32

	// Limit.
	//
	// Format: int32
	Limit int32

	// Tags.
	Tags []int32

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the find params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindParams) WithDefaults() *FindParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find params.
func (o *FindParams) WithTimeout(timeout time.Duration) *FindParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find params.
func (o *FindParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the find params.
//
// Deprecated: use the operation call with context to pass the context instead of [FindParams].
func (o *FindParams) WithContext(ctx context.Context) *FindParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find params.
//
// Deprecated: use the operation call with context to pass the context instead of [FindParams].
func (o *FindParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the find params.
func (o *FindParams) WithHTTPClient(client *http.Client) *FindParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find params.
func (o *FindParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRateLimit adds the xRateLimit to the find params.
func (o *FindParams) WithXRateLimit(xRateLimit int32) *FindParams {
	o.SetXRateLimit(xRateLimit)
	return o
}

// SetXRateLimit adds the xRateLimit to the find params.
func (o *FindParams) SetXRateLimit(xRateLimit int32) {
	o.XRateLimit = xRateLimit
}

// WithLimit adds the limit to the find params.
func (o *FindParams) WithLimit(limit int32) *FindParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the find params.
func (o *FindParams) SetLimit(limit int32) {
	o.Limit = limit
}

// WithTags adds the tags to the find params.
func (o *FindParams) WithTags(tags []int32) *FindParams {
	o.SetTags(tags)
	return o
}

// SetTags adds the tags to the find params.
func (o *FindParams) SetTags(tags []int32) {
	o.Tags = tags
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *FindParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Rate-Limit
	if err := r.SetHeaderParam("X-Rate-Limit", conv.FormatInteger(o.XRateLimit)); err != nil {
		return err
	}

	// form param limit
	frLimit := o.Limit
	fLimit := conv.FormatInteger(frLimit)
	if err := r.SetFormParam("limit", fLimit); err != nil {
		return err
	}

	if o.Tags != nil {

		// binding items for tags
		joinedTags := o.bindParamTags(reg)

		// form array param tags
		if err := r.SetFormParam("tags", joinedTags...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamFind binds the parameter tags.
func (o *FindParams) bindParamTags(formats strfmt.Registry) []string {
	tagsIR := o.Tags

	var tagsIC []string
	for _, tagsIIR := range tagsIR { // explode []int32

		tagsIIV := conv.FormatInteger(tagsIIR) // int32 as string
		tagsIC = append(tagsIC, tagsIIV)
	}

	// items.CollectionFormat: "multi"
	tagsIS := stringutils.JoinByFormat(tagsIC, "multi")

	return tagsIS
}
