// Code generated by go-swagger; DO NOT EDIT.
//
// This file contains an experimental manual adaptation for
// x-go-server-streaming until go-swagger code generation supports it.

package uploads

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// UploadFileMaxBodySize caps the size of the form body.
//
// The default value is 32 MB. Larger bodies will error with http status 413.
var UploadFileMaxBodySize int64 = 32 << 20

// NewUploadFileParams creates a new UploadFileParams object
//
// There are no default values defined in the spec.
func NewUploadFileParams() UploadFileParams {
	return UploadFileParams{}
}

// UploadFileParams contains all the bound params for the upload file operation
// typically these are obtained from a http.Request
//
// swagger:parameters uploadFile
type UploadFileParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	// MultipartForm owns the request-body stream. Generated binding deliberately
	// does not consume or validate file and field parts: the handler owns
	// traversal, validation, draining and closing.
	MultipartForm *runtime.MultipartFormStream `json:"-"`
}

// BindRequest binds the request-level multipart stream without consuming parts.
//
// Streaming operations intentionally leave file and field validation to the
// handler because multipart parts are ordered and may be mixed or repeated.
func (o *UploadFileParams) BindRequest(r *http.Request, _ *middleware.MatchedRoute) error {
	o.HTTPRequest = r

	stream, err := runtime.NewMultipartFormStream(
		r,
		// The example applies the request-size limit with http.MaxBytesHandler.
		runtime.MultipartFormStreamMaxBody(-1),
	)
	if err != nil {
		return err
	}

	o.MultipartForm = stream

	return nil
}
