// Code generated by go-swagger; DO NOT EDIT.
//
// This file contains an experimental manual adaptation for
// x-go-server-streaming until go-swagger code generation supports it.

package uploads

import (
	stderrors "errors"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// UploadFileMaxBodySize caps the size of the form body.
//
// The default value is 32 MB. Larger bodies will error with http status 413.
var UploadFileMaxBodySize int64 = 32 << 20

// NewUploadFileParams creates a new UploadFileParams object
//
// There are no default values defined in the spec.
func NewUploadFileParams() UploadFileParams {

	return UploadFileParams{}
}

// UploadFileParams contains all the bound params for the upload file operation
// typically these are obtained from a http.Request
//
// swagger:parameters uploadFile
type UploadFileParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	// MultipartForm owns the request-body stream. The handler must call Drain
	// after successfully consuming File, or Close to abort processing.
	MultipartForm *runtime.MultipartFormStream `json:"-"`

	// Required: true
	// In: formData
	File *runtime.StreamedFile
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadFileParams() beforehand.
func (o *UploadFileParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	o.HTTPRequest = r

	stream, err := runtime.NewMultipartFormStream(
		r,
		// The example applies the request-size limit with http.MaxBytesHandler.
		runtime.MultipartFormStreamMaxBody(-1),
	)
	if err != nil {
		return err
	}
	o.MultipartForm = stream

	file, err := nextStreamingFile(stream, "file")
	if err != nil {
		return closeMultipartStream(stream, err)
	}
	o.File = file

	return nil
}

func nextStreamingFile(stream *runtime.MultipartFormStream, fieldName string) (*runtime.StreamedFile, error) {
	for {
		file, err := stream.NextFile()
		if stderrors.Is(err, io.EOF) {
			return nil, errors.Required(fieldName, "formData", nil)
		}
		if err != nil {
			return nil, err
		}
		if file.FieldName == fieldName {
			return file, nil
		}
		if err := file.Close(); err != nil {
			return nil, err
		}
	}
}

func closeMultipartStream(stream *runtime.MultipartFormStream, err error) error {
	if closeErr := stream.Close(); closeErr != nil {
		return stderrors.Join(err, closeErr)
	}

	return err
}
