// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// UploadFileMaxBodySize caps the size of the form body.
//
// The default value is 32 MB. Larger bodies will error with http status 413.
var UploadFileMaxBodySize int64 = 32 << 20

// NewUploadFileParams creates a new UploadFileParams object
//
// There are no default values defined in the spec.
func NewUploadFileParams() UploadFileParams {

	return UploadFileParams{}
}

// UploadFileParams contains all the bound params for the upload file operation
// typically these are obtained from a http.Request
//
// swagger:parameters uploadFile
type UploadFileParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	// MultipartForm is the lazily consumed multipart form stream.
	//
	// The handler owns traversal, validation and closing or draining this stream.
	MultipartForm *runtime.MultipartFormStream `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadFileParams() beforehand.
func (o *UploadFileParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}

	multipartForm, err := runtime.NewMultipartFormStream(
		r,
		runtime.MultipartFormStreamMaxBody(UploadFileMaxBodySize),
	)
	if err != nil {
		return err
	}
	o.MultipartForm = multipartForm
	return nil
}
