// Code generated by go-swagger; DO NOT EDIT.

package greeter

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-swagger/examples/middleware/models"
)

// GreetNameOKCode is the HTTP code returned for type GreetNameOK
const GreetNameOKCode int = 200

// GreetNameOK greeting
//
// swagger:response greetNameOK
type GreetNameOK struct {

	// In: Body
	Payload *models.Greeting `json:"body,omitempty"`
}

// NewGreetNameOK creates GreetNameOK with default headers values
func NewGreetNameOK() *GreetNameOK {

	return &GreetNameOK{}
}

// WithPayload adds the payload to the greet name o k response
func (o *GreetNameOK) WithPayload(payload *models.Greeting) *GreetNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the greet name o k response
func (o *GreetNameOK) SetPayload(payload *models.Greeting) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GreetNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GreetNameDefault error
//
// swagger:response greetNameDefault
type GreetNameDefault struct {
	_statusCode int

	// In: Body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGreetNameDefault creates GreetNameDefault with default headers values
func NewGreetNameDefault(code int) *GreetNameDefault {
	if code <= 0 {
		code = 500
	}

	return &GreetNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the greet name default response
func (o *GreetNameDefault) WithStatusCode(code int) *GreetNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the greet name default response
func (o *GreetNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the greet name default response
func (o *GreetNameDefault) WithPayload(payload *models.Error) *GreetNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the greet name default response
func (o *GreetNameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GreetNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
