// Code generated by go-swagger; DO NOT EDIT.

package greeter

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GreetNameHandlerFunc turns a function with the right signature into a greet name handler
type GreetNameHandlerFunc func(GreetNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GreetNameHandlerFunc) Handle(params GreetNameParams) middleware.Responder {
	return fn(params)
}

// GreetNameHandler interface for that can handle valid greet name params
type GreetNameHandler interface {
	Handle(GreetNameParams) middleware.Responder
}

// NewGreetName creates a new http.Handler for the greet name operation
func NewGreetName(ctx *middleware.Context, handler GreetNameHandler) *GreetName {
	return &GreetName{Context: ctx, Handler: handler}
}

// GreetName swagger:route GET /greet/{name} greeter greetName
//
// Return a greeting addressed to the caller.
type GreetName struct {
	Context *middleware.Context
	Handler GreetNameHandler
}

func (o *GreetName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGreetNameParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
