// Code generated by go-swagger; DO NOT EDIT.

package greeter

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-swagger/examples/middleware/models"
)

// GreetOKCode is the HTTP code returned for type GreetOK
const GreetOKCode int = 200

// GreetOK greeting
//
// swagger:response greetOK
type GreetOK struct {

	// In: Body
	Payload *models.Greeting `json:"body,omitempty"`
}

// NewGreetOK creates GreetOK with default headers values
func NewGreetOK() *GreetOK {

	return &GreetOK{}
}

// WithPayload adds the payload to the greet o k response
func (o *GreetOK) WithPayload(payload *models.Greeting) *GreetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the greet o k response
func (o *GreetOK) SetPayload(payload *models.Greeting) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GreetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GreetDefault error
//
// swagger:response greetDefault
type GreetDefault struct {
	_statusCode int

	// In: Body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGreetDefault creates GreetDefault with default headers values
func NewGreetDefault(code int) *GreetDefault {
	if code <= 0 {
		code = 500
	}

	return &GreetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the greet default response
func (o *GreetDefault) WithStatusCode(code int) *GreetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the greet default response
func (o *GreetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the greet default response
func (o *GreetDefault) WithPayload(payload *models.Error) *GreetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the greet default response
func (o *GreetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GreetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
