// Code generated by go-swagger; DO NOT EDIT.

package todos

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindHandlerFunc turns a function with the right signature into a find handler
type FindHandlerFunc func(FindParams) (middleware.Responder, error)

// Handle executing the request and returning a response
func (fn FindHandlerFunc) Handle(params FindParams) (middleware.Responder, error) {
	return fn(params)
}

// FindHandler interface for that can handle valid find params
type FindHandler interface {
	Handle(FindParams) (middleware.Responder, error)
}

// NewFind creates a new http.Handler for the find operation
func NewFind(ctx *middleware.Context, handler FindHandler) *Find {
	return &Find{Context: ctx, Handler: handler}
}

/*
	Find swagger:route GET / todos find

Find find API
*/
type Find struct {
	Context *middleware.Context
	Handler FindHandler
}

func (o *Find) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewFindParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res, err := o.Handler.Handle(params) // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	o.Context.Respond(rw, r, route.Produces, route, res)

}
