// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewElapseParams creates a new ElapseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewElapseParams() *ElapseParams {
	return NewElapseParamsWithTimeout(cr.DefaultTimeout)
}

// NewElapseParamsWithTimeout creates a new ElapseParams object
// with the ability to set a timeout on a request.
func NewElapseParamsWithTimeout(timeout time.Duration) *ElapseParams {
	return &ElapseParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewElapseParamsWithContext creates a new ElapseParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ElapseParams].
func NewElapseParamsWithContext(ctx context.Context) *ElapseParams {
	return &ElapseParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewElapseParamsWithHTTPClient creates a new ElapseParams object
// with the ability to set a custom HTTPClient for a request.
func NewElapseParamsWithHTTPClient(client *http.Client) *ElapseParams {
	return &ElapseParams{
		HTTPClient: client,
	}
}

/*
ElapseParams contains all the parameters to send to the API endpoint

	for the elapse operation.

	Typically these are written to a http.Request.
*/
type ElapseParams struct {

	// Length.
	//
	// How many seconds to count down
	Length int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the elapse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ElapseParams) WithDefaults() *ElapseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the elapse params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ElapseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the elapse params.
func (o *ElapseParams) WithTimeout(timeout time.Duration) *ElapseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the elapse params.
func (o *ElapseParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the elapse params.
//
// Deprecated: use the operation call with context to pass the context instead of [ElapseParams].
func (o *ElapseParams) WithContext(ctx context.Context) *ElapseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the elapse params.
//
// Deprecated: use the operation call with context to pass the context instead of [ElapseParams].
func (o *ElapseParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the elapse params.
func (o *ElapseParams) WithHTTPClient(client *http.Client) *ElapseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the elapse params.
func (o *ElapseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLength adds the length to the elapse params.
func (o *ElapseParams) WithLength(length int64) *ElapseParams {
	o.SetLength(length)
	return o
}

// SetLength adds the length to the elapse params.
func (o *ElapseParams) SetLength(length int64) {
	o.Length = length
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ElapseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param length
	if err := r.SetPathParam("length", conv.FormatInteger(o.Length)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
