// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new operations API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new operations API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for operations API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// Elapse count down the number of seconds.
	Elapse(params *ElapseParams, writer io.Writer, opts ...ClientOption) (*ElapseOK, error)

	// ElapseContext count down the number of seconds.
	ElapseContext(ctx context.Context, params *ElapseParams, writer io.Writer, opts ...ClientOption) (*ElapseOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
Elapsecounts down the number of seconds.

Count down the seconds remaining.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.ElapseContext] instead.
*/
func (a *Client) Elapse(params *ElapseParams, writer io.Writer, opts ...ClientOption) (*ElapseOK, error) {
	var ctx context.Context
	if params.Context != nil {
		ctx = params.Context
	} else {
		ctx = context.Background()
	}

	return a.ElapseContext(ctx, params, writer, opts...)
}

/*
ElapseContextcounts down the number of seconds.

Count down the seconds remaining.

Do not use the deprecated [ElapseParams.Context] with this method: it would be ignored.
*/
func (a *Client) ElapseContext(ctx context.Context, params *ElapseParams, writer io.Writer, opts ...ClientOption) (*ElapseOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewElapseParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "elapse",
		Method:             "GET",
		PathPattern:        "/elapse/{length}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ElapseReader{formats: a.formats, writer: writer},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ElapseOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for elapse: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}
