// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Item item
//
// swagger:model Item
type Item string

// Validate validates this item
func (m Item) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this item based on context it is used
func (m Item) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}
