// Code generated by go-swagger; DO NOT EDIT.

package pet

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/stringutils"
)

// NewPetListParams creates a new PetListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPetListParams() *PetListParams {
	return NewPetListParamsWithTimeout(cr.DefaultTimeout)
}

// NewPetListParamsWithTimeout creates a new PetListParams object
// with the ability to set a timeout on a request.
func NewPetListParamsWithTimeout(timeout time.Duration) *PetListParams {
	return &PetListParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPetListParamsWithContext creates a new PetListParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PetListParams].
func NewPetListParamsWithContext(ctx context.Context) *PetListParams {
	return &PetListParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPetListParamsWithHTTPClient creates a new PetListParams object
// with the ability to set a custom HTTPClient for a request.
func NewPetListParamsWithHTTPClient(client *http.Client) *PetListParams {
	return &PetListParams{
		HTTPClient: client,
	}
}

/*
PetListParams contains all the parameters to send to the API endpoint

	for the pet list operation.

	Typically these are written to a http.Request.
*/
type PetListParams struct {

	/* Status.

	   Status values that need to be considered for filter
	*/
	Status []string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the pet list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PetListParams) WithDefaults() *PetListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pet list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PetListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pet list params.
func (o *PetListParams) WithTimeout(timeout time.Duration) *PetListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pet list params.
func (o *PetListParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the pet list params.
//
// Deprecated: use the operation call with context to pass the context instead of [PetListParams].
func (o *PetListParams) WithContext(ctx context.Context) *PetListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pet list params.
//
// Deprecated: use the operation call with context to pass the context instead of [PetListParams].
func (o *PetListParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the pet list params.
func (o *PetListParams) WithHTTPClient(client *http.Client) *PetListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pet list params.
func (o *PetListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStatus adds the status to the pet list params.
func (o *PetListParams) WithStatus(status []string) *PetListParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the pet list params.
func (o *PetListParams) SetStatus(status []string) {
	o.Status = status
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PetListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Status != nil {

		// binding items for status
		joinedStatus := o.bindParamStatus(reg)

		// query array param status
		if err := r.SetQueryParam("status", joinedStatus...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamPetList binds the parameter status.
func (o *PetListParams) bindParamStatus(formats strfmt.Registry) []string {
	statusIR := o.Status

	var statusIC []string
	for _, statusIIR := range statusIR { // explode []string

		statusIIV := statusIIR // string as string
		statusIC = append(statusIC, statusIIV)
	}

	// items.CollectionFormat: "multi"
	statusIS := stringutils.JoinByFormat(statusIC, "multi")

	return statusIS
}
