# SPDX-FileCopyrightText: Copyright 2015-2026 go-swagger maintainers
# SPDX-License-Identifier: Apache-2.0

name: Contributors

on:
  schedule:
    - cron: '18 4 * * 6'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  contributors:
    permissions:
      pull-requests: write
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/contributors.yml@7a1bb6c4f078ac1a3258db1ae91c37a9d29eee2a # v0.3.4
    secrets:
      github-app-id: ${{ secrets.CI_BOT_APP_ID }}
      github-app-private-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}
      gpg-private-key: ${{ secrets.CI_BOT_GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ secrets.CI_BOT_GPG_PASSPHRASE }}
      gpg-fingerprint: ${{ secrets.CI_BOT_SIGNING_KEY }}
